
on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize
    branches: ["master"]

jobs:
  compile:
    name: Compile - ${{ matrix.platform.release_for }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: pacejka_tuner
            command: build

          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: pacejka_tuner
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: pacejka_tuner.exe
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: pacejka_tuner
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Move out build binary
        run: |
          cd target/${{ matrix.platform.target }}/release
          ls
          mkdir ../../../dist/
          mv ${{ matrix.platform.bin }} ../../../dist/${{ matrix.platform.bin }}


      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pacejka-tuner-${{ matrix.platform.release_for }}
          path: dist/${{ matrix.platform.bin }}
          if-no-files-found: error

  compile-success:
    runs-on: ubuntu-latest
    needs: compile
    name: Successful Compilation
    steps:
      - run: echo "Done!"
