name: Deploy Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Cargo Tests
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run test
        run: cargo test --no-fail-fast --workspace

  compile:
    name: Cross Compile Binaries
    needs:
      - test
    uses: ./.github/workflows/compile.yaml
    secrets: inherit

  deploy:
    name: Deploy Release
    needs:
      - test
      - compile
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download compiled artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dasel and get Cargo version
        id: get-version
        run: |
          curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
          mv ./dasel /usr/local/bin/dasel
          export VERSION=$(dasel -f Cargo.toml -r toml '.package.version')
          echo "version=${VERSION//\'/}" >> $GITHUB_OUTPUT

      - name: Deploy release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.DEPLOY_PAT }}"
          prerelease: false
          draft: true
          automatic_release_tag: ${{ steps.get-version.outputs.version }}
