name: Test Pipeline

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

concurrency:
  group: test-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Cargo Tests
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run test
        run: cargo test --no-fail-fast --workspace

  compile:
    name: Cross Compile Binaries
    needs:
      - test
    uses: ./.github/workflows/compile.yaml
    secrets: inherit
